# Generated by Django 5.2 on 2025-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VinotecaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('variedad', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=13)),
                ('formato', models.CharField(max_length=50)),
                ('tamaño_ml', models.CharField(max_length=50)),
                ('ean', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
