# Generated by Django 5.2 on 2025-04-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VinotecaProductos',
            new_name='VinotecaProducto',
        ),
    ]
