# Generated by Django 5.2 on 2025-04-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0004_vinotecaproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinotecaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('DNI', models.IntegerField()),
                ('mail', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('codigo_postal', models.IntegerField()),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
