# Generated by Django 5.2 on 2025-04-27 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0005_vinotecacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinotecacliente',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
    ]
